### ISSUE TITLE
Cannot zoom when using latest version of Firefox. 

### ISSUE THREAD

**Issue by JacobHenner** [Randati/fc00.org#2]
When using the latest version of Firefox, the graph of the network cannot be enlarged by scrolling. The functionality works as expected in the latest version of Chromium.

**Comment by JacobHenner** [comment]
It seems as if this is caused by: 
`function handleScroll(e) {
		var mouse = mousePos(e);
		var e = window.event;
		var delta = Math.max(-1, Math.min(1, (e.wheelDelta || -e.detail)));`
Which results in "TypeError: e is undefined" on Firefox.

**Comment by Randati** [comment]
Thanks! Fixed in 26516849789d66be63cc55aa927da3bca4d9f0c7. I'm kind of surprised that it worked in any browser.
