### ISSUE TITLE
fc00.org no longer opens from hyperboria

### ISSUE THREAD

**Issue by atommixz** [Randati/fc00.org#4]
why?

**Comment by whoizit** [comment]
replay

**Comment by Randati** [comment]
Sorry for the long delay. I believe this has something to do with the server restarting because of the Venom vulnerability. Unfortunately, I don't have time or interest to continue running the site so I don't have any plans to get it up again.

If someone wants to continue running this site or has some other related plans, I'll gladly give out the domain.

**Comment by fbt** [comment]
fc00.dryware.org now tells people what happened to fc00.org.
It's configured to answer on fc00.org and www.fc00.org (on clearnet) as well.

So if you want, you can point the domain to me till someone takes up the project.

**Comment by Randati** [comment]
Thanks @fbt!  I made simple redirects. `fc00.org` is untested. `www.fc00.org` redirects straight here.

```
fc00.org -> http://dryware.org/pages/fc00.html
www.fc00.org -> https://github.com/Randati/fc00.org/issues/4#issuecomment-114139894
```

**Comment by fbt** [comment]
Yep, fc00.org redirect works.

**Comment by zielmicha** [comment]
I have set up fc00 on http://fc00.atomshare.net/ (http://h.fc00.atomshare.net/ via Hyperboria). 
@Randati It would be nice if you could make database dump from fc00.org public

I've also made adjustments to sendGraph.py script, so it works with current CJDNS version (https://github.com/zielmicha/fc00.org/blob/master/scripts/sendGraph.py).

**Comment by Randati** [comment]
Cool!
I'm not sure whether I still have the database anywhere but I can check that later.
In any case, I think the dump would have only some historical value and not really help populating the map anymore. Running the scripts for a few days or a week would probably have a bigger effect (at least if cjdns hasn't changed a lot).

**Comment by zielmicha** [comment]
I've tried tuning discovery rate in CJDNS code, but it didn't help. Maybe I need to setup more peers. 

By the way, the web server will also respond to {www.,h.,}fc00.org. I can accept domain transfer, if you don't want to pay for it.

**Comment by whoizit** [comment]
zielmicha, I run it by cron. I have ~10 node worldwide. Guys from IRC also known about you're site and fork
23 \* \* \* \* $HOME/bin/sendGraph.py

**Comment by whoizit** [comment]
It should be closed
